import { useEffect, useState, useRef } from 'react';

import Chat from './components/Chat';
import ArrowRightIcon from './components/icons/ArrowRightIcon';
import StopIcon from './components/icons/StopIcon';
import Progress from './components/Progress';

const IS_WEBGPU_AVAILABLE = !!navigator.gpu;
const STICKY_SCROLL_THRESHOLD = 120;

function App() {

  const worker = useRef(null);
  const textareaRef = useRef(null);
  const chatContainerRef = useRef(null);

  const [status, setStatus] = useState(null);
  const [loadingMessage, setLoadingMessage] = useState('');
  const [progressItems, setProgressItems] = useState([]);
  const [isRunning, setIsRunning] = useState(false);

  const [input, setInput] = useState('Tell me about teapotllm');
  const [context, setContext] = useState(`Teapot is an open-source small language model (~800 million parameters) fine-tuned on synthetic data and optimized to run locally on resource-constrained devices such as smartphones and CPUs. Teapot is trained to only answer using context from documents, reducing hallucinations. Teapot can perform a variety of tasks, including hallucination-resistant Question Answering (QnA), Retrieval-Augmented Generation (RAG), and JSON extraction. TeapotLLM is a fine tune of flan-t5-large that was trained on synthetic data generated by Deepseek v3 TeapotLLM can be hosted on low-power devices with as little as 2GB of CPU RAM such as a Raspberry Pi. Teapot is a model built by and for the community.`);
  const [messages, setMessages] = useState([]);
  const [tps, setTps] = useState(null);
  const [numTokens, setNumTokens] = useState(null);

  function onEnter(message, context) {
    setMessages(prev => [
      ...prev,
      { "role": "user", "content": message, "context": context },
    ]);
    setTps(null);
    setIsRunning(true);
    setInput('');
  }

  useEffect(() => {
    resizeInput();
  }, [input]);

  function onInterrupt() {
    worker.current.postMessage({ type: 'interrupt' });
  }

  function resizeInput() {
    if (!textareaRef.current) return;
    const target = textareaRef.current;
    target.style.height = 'auto';
    const newHeight = Math.min(Math.max(target.scrollHeight, 24), 200);
    target.style.height = `${newHeight}px`;
  }

  useEffect(() => {
    if (!worker.current) {
      worker.current = new Worker(new URL('./worker.js', import.meta.url), { type: 'module' });
    }

    const onMessageReceived = (e) => {
      switch (e.data.status) {
        case 'loading':
          setStatus('loading');
          setLoadingMessage(e.data.data);
          break;
        case 'initiate':
          setProgressItems(prev => [...prev, e.data]);
          break;
        case 'progress':
          setProgressItems(prev => prev.map(item =>
            item.file === e.data.file ? { ...item, ...e.data } : item
          ));
          break;
        case 'done':
          setProgressItems(prev => prev.filter(item => item.file !== e.data.file));
          break;
        case 'ready':
          setStatus('ready');
          break;
        case 'start':
          setMessages(prev => [...prev, { "role": "assistant", "content": "" }]);
          break;
        case 'update': {
          const { output, tps, numTokens } = e.data;
          setTps(tps);
          setNumTokens(numTokens);
          setMessages(prev => {
            const cloned = [...prev];
            const last = cloned.at(-1);
            cloned[cloned.length - 1] = { ...last, content: last.content + output };
            return cloned;
          });
          break;
        }
        case 'complete':
          setIsRunning(false);
          break;
      }
    };

    worker.current.addEventListener('message', onMessageReceived);
    return () => {
      worker.current.removeEventListener('message', onMessageReceived);
    };
  }, []);

  useEffect(() => {
    if (messages.filter(x => x.role === 'user').length === 0) return;
    if (messages.at(-1).role === 'assistant') return;
    setTps(null);
    worker.current.postMessage({ type: 'generate', data: messages });
  }, [messages, isRunning]);

  useEffect(() => {
    if (!chatContainerRef.current) return;
    if (isRunning) {
      const element = chatContainerRef.current;
      if (element.scrollHeight - element.scrollTop - element.clientHeight < STICKY_SCROLL_THRESHOLD) {
        element.scrollTop = element.scrollHeight;
      }
    }
  }, [messages, isRunning]);

  return (
    IS_WEBGPU_AVAILABLE ? (
      <div
        className="flex flex-col h-screen mx-auto justify-end text-gray-800 dark:text-gray-200"
        style={{ backgroundColor: '#f2f2f2', color:"#111" }}
      >
        {status === null && messages.length === 0 && (
          <div className="h-full overflow-auto scrollbar-thin flex justify-center items-center flex-col relative">
            {/* <div className="flex flex-col items-center mb-1 text-center">
              <img src="https://cdn-avatars.huggingface.co/v1/production/uploads/605383845e96cd4dd1fc6d5c/je8Szo8Db8CjU4l0d-fd2.jpeg" width="150" height="150" className="block mb-4 rounded-lg" />
              <h1 className="text-4xl font-bold mb-1">TeapotLLM WebGPU</h1>
              <h2 className="font-semibold">A private and RAG AI chatbot that runs locally in your browser.</h2>
            </div> */}

            <div className="flex flex-col items-center px-4">
              <p className="max-w-[514px] mb-4">
                <br />
                You are about to load <a href="https://huggingface.co/teapotai/teapotllm" target="_blank" rel="noreferrer" className="font-medium underline">teapotai/teapotllm</a>,
                a 783M parameter LLM that is optimized for inference on the web. Everything runs directly in your browser using <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noreferrer" className="underline">🤗 Transformers.js</a> and ONNX Runtime Web.<br /><br />
              </p>

              <button
                className="border px-4 py-2 rounded-lg bg-blue-400 text-white hover:bg-blue-500 disabled:bg-blue-100 disabled:cursor-not-allowed select-none"
                onClick={() => {
                  worker.current.postMessage({ type: 'load' });
                  setStatus('loading');
                }}
                disabled={status !== null}
              >
                Load model (736.85 MB)
              </button>
            </div>
          </div>
        )}

        {status === 'loading' && (
          <div className="w-full max-w-[500px] text-left mx-auto p-4 bottom-0 mt-auto">
            <p className="text-center mb-1">{loadingMessage}</p>
            {progressItems.map(({ file, progress, total }, i) => (
              <Progress key={i} text={file} percentage={progress} total={total} />
            ))}
          </div>
        )}

        {status === 'ready' && (
          <div
            ref={chatContainerRef}
            className="overflow-y-auto scrollbar-thin w-full flex flex-col items-center h-full"
          >
            <Chat messages={messages} />
            <p className="text-center text-sm min-h-6">
              {tps && messages.length > 0 && (
                <>
                  {!isRunning && (
                    <span>Generated {numTokens} tokens in {(numTokens / tps).toFixed(2)} seconds&nbsp;&#40;</span>
                  )}
                  <span className="font-medium text-center mr-1 text-black">{tps.toFixed(2)}</span>
                  <span className="">tokens/second</span>
                  {!isRunning && (
                    <>
                      <span className="mr-1">&#41;.</span>
                      <span className="underline cursor-pointer" onClick={() => {
                        worker.current.postMessage({ type: 'reset' });
                        setMessages([]);
                      }}>Reset</span>
                    </>
                  )}
                </>
              )}
            </p>
          </div>
        )}

        <div className="mt-2 border bg-[#f2f2f2] dark:bg-gray-700 rounded-lg w-[600px] max-w-[80%] max-h-[200px] mx-auto relative mb-3 flex flex-col">
          <label className="px-3 pt-2 text-sm text-gray-600 dark:text-gray-300">Context</label>
          <textarea
            className="scrollbar-thin w-full px-3 py-1 rounded-lg bg-transparent border-none outline-none text-gray-800 disabled:text-gray-400 dark:text-gray-200 placeholder-gray-500 dark:placeholder-gray-400 disabled:placeholder-gray-200 resize-none disabled:cursor-not-allowed"
            placeholder="Add context..."
            type="text"
            rows={4}
            value={context}
            disabled={status !== 'ready'}
            onChange={(e) => setContext(e.target.value)}
          />
          <div className="relative">
            <label className="px-3 text-sm text-gray-600 dark:text-gray-300">Message</label>
            <textarea
              ref={textareaRef}
              className="scrollbar-thin w-full px-3 py-1 rounded-lg bg-transparent border-none outline-none text-gray-800 disabled:text-gray-400 dark:text-gray-200 placeholder-gray-500 dark:placeholder-gray-400 disabled:placeholder-gray-200 resize-none disabled:cursor-not-allowed"
              placeholder="Type your message..."
              type="text"
              rows={1}
              value={input}
              disabled={status !== 'ready'}
              title={status === 'ready' ? "Model is ready" : "Model not loaded yet"}
              onKeyDown={(e) => {
                if (input.length > 0 && !isRunning && (e.key === "Enter" && !e.shiftKey)) {
                  e.preventDefault();
                  onEnter(input, context);
                }
              }}
              onInput={(e) => setInput(e.target.value)}
            />
            {isRunning ? (
              <div className="cursor-pointer" onClick={onInterrupt}>
                <StopIcon className="h-8 w-8 p-1 rounded-md text-gray-800 dark:text-gray-100 absolute right-3 bottom-3" />
              </div>
            ) : input.length > 0 ? (
              <div className="cursor-pointer" onClick={() => onEnter(input, context)}>
                <ArrowRightIcon className="h-8 w-8 p-1 bg-gray-800 dark:bg-gray-100 text-white dark:text-black rounded-md absolute right-3 bottom-3" />
              </div>
            ) : (
              <div>
                <ArrowRightIcon className="h-8 w-8 p-1 bg-gray-200 dark:bg-gray-600 text-gray-50 dark:text-gray-800 rounded-md absolute right-3 bottom-3" />
              </div>
            )}
          </div>
        </div>

        <p className="text-xs text-gray-400 text-center mb-3">
          Disclaimer: Generated content may be inaccurate or false.
        </p>
      </div>
    ) : (
      <div className="fixed w-screen h-screen bg-black z-10 bg-opacity-[92%] text-white text-2xl font-semibold flex justify-center items-center text-center">
        WebGPU is not supported<br />by this browser :(
      </div>
    )
  );
}

export default App;
