remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Teapot AI
description: <a style="color:rgb(242,242,242);" href="./">Home</a> |  <a style="color:rgb(242,242,242);" href="./blog">Blog</a> |  <a style="color:rgb(242,242,242);" href="./docs">Docs</a> |  <a style="color:rgb(242,242,242);" href="https://discord.gg/hPxGSn5dST">Demo on Discord</a><script src="./include.js"></script>
